# Generated by Django 5.2.5 on 2025-08-17 02:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('isbn', models.CharField(db_index=True, max_length=13)),
                ('total_pages', models.PositiveIntegerField()),
                ('current_page', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('reading', 'Currently Reading'), ('completed', 'Completed'), ('want_to_read', 'Want to Read')], default='want_to_read', max_length=20)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Book',
                'ordering': ['-date_added'],
                'unique_together': {('user', 'isbn')},
            },
        ),
    ]
