# Generated by Django 5.2.5 on 2025-08-19 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_rename_user_id_book_user_remove_userprofile_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, db_index=True, max_length=13),
        ),
        migrations.AlterField(
            model_name='book',
            name='total_pages',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
