# Generated by Django 5.2.5 on 2025-08-19 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_isbn_alter_book_total_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='book',
            name='total_pages',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
