# Generated by Django 5.2.5 on 2025-08-19 07:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_book_id_alter_book_total_pages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('user', 'title', 'author')},
        ),
    ]
